### ISSUE TITLE
Remove JavaCL?

### ISSUE THREAD

**Issue by skalarproduktraum** [ClearControl/clearcl#3]
Hey Loic,

I noticed that JavaCL (and with that, nativelibs4java-utils, and so on) are introducing quite a dirty dependency tree, leading to the Maven enforcer rules to complain about duplicate classes, which is quite bad. Shall we remove JavaCL maybe in general? Take into consideration it's unmaintained for more than two years, and there you have much better (and more stable) backends available 👍

**Comment by royerloic** [comment]
problem is that JOCL does not work everywhere...

**Comment by skalarproduktraum** [comment]
Okay, so I added a workaround for now that makes maven-enforcer-plugin ignore classes from nativelibs4java, bridj, and so on -- see https://github.com/scenerygraphics/scenery/commit/a8320a357844f40f6df22b5ec3faa60bc493a1ac.

In the long run, it'd be nice though if we could get rid of JavaCL, also taking into consideration it's still stuck at OpenCL 1.1. Do you remember by chance what the specific issues with JOCL were? I'm using it for the font rendering in scenery and didn't really encounter a problem so far.

**Comment by skalarproduktraum** [comment]
Hey @royerloic,

the JOCL problem is not by chance about a crash in `setKernelArgument`, is it? Because that one arises due to a wrong value being returned by `Size.of` for primitive types in CoreMem. I'm fixing that right now...

**Comment by royerloic** [comment]
Yes, it could be, Size.of needs more testing, not the first time that a bug lurks there...

**Comment by royerloic** [comment]
I believe this is fixed, I will close for now
